application: project-name-should-be-here
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:       # static then dynamic

# api from cloud endpoints
- url: /_ah/spi/.*
  script: main.API
  secure: always

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: frontend/src/app/index.html
  upload: frontend/index\.html
  secure: always

- url: /_ah/spi/.*
  script: conference.api
  secure: always

libraries:
  - name: endpoints
    version: latest

skip_files:
- ^.git$
- ^frontend$
- ^(.*/)?.*\.py[co]$
- README.md
- .gitignore
- .nvmrc
- .python-version
- pylama.ini
- requirements.txt
- report.txt
- ^worker$
- worker.yaml
- queue.yaml
- ^lib_tests$
- ^tests$
